apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xllq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xllq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xllq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xllq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xllq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xhpf-tenant/rhtap-demo-app/hacbs-test-project-xllq@sha256:43333e06e209a516ffcca6d3302e947e4e60c9ebc811be25a97d51cb95b46f47
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
